In [20]:
#!mamba install pandas  #uncomment when in Jupyter
import pandas as pd
datafile=pd.read_csv ("https://raw.githubusercontent.com/Psyc3000A/Data/refs/heads/main/sleep.csv")
datafile.groupby('group').describe()

          A                                                extra        ...  \
      count  mean      std   min    25%   50%    75%   max count  mean  ...
group                                                                   ...
1      10.0   5.5  3.02765   1.0   3.25   5.5   7.75  10.0  10.0  0.75  ...
2      10.0  15.5  3.02765  11.0  13.25  15.5  17.75  20.0  10.0  2.33  ...

                    ID
        75%  max count mean      std  min   25%  50%   75%   max
group
1      1.70  3.7  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0
2      4.15  5.5  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0

[2 rows x 24 columns]

In [21]:
datafile.boxplot(column="extra")

In [22]:
datafile.boxplot(column="extra", showmeans=True)

In [23]:
datafile["extra"].plot(kind="density")

In [24]:
datafile.groupby("group")["extra"].plot(kind="density", legend=True)

group
1    Axes(0.125,0.11;0.775x0.77)
2    Axes(0.125,0.11;0.775x0.77)
Name: extra, dtype: object

In [25]:
datafile.groupby('group').describe()

          A                                                extra        ...  \
      count  mean      std   min    25%   50%    75%   max count  mean  ...
group                                                                   ...
1      10.0   5.5  3.02765   1.0   3.25   5.5   7.75  10.0  10.0  0.75  ...
2      10.0  15.5  3.02765  11.0  13.25  15.5  17.75  20.0  10.0  2.33  ...

                    ID
        75%  max count mean      std  min   25%  50%   75%   max
group
1      1.70  3.7  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0
2      4.15  5.5  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0

[2 rows x 24 columns]

In [26]:
datafile.groupby('group')['extra'].describe()

       count  mean       std  min    25%   50%   75%  max
group
1       10.0  0.75  1.789010 -1.6 -0.175  0.35  1.70  3.7
2       10.0  2.33  2.002249 -0.1  0.875  1.75  4.15  5.5

In [27]:
datafile["extra"].hist()